### ISSUE TITLE
Create PgSQL GIN index difference between yii2 and yii3

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/db-migration#104]
Good day. When i try to create GIN index using MigrationBuilder  like yii2 style:

`$b->createIndex('address_classifier_vector_idx', 'address_classifier', 'vector', 'GIN');`

I have error with type hint of 4th unique argument (bool).

So - maybe create MigrationBuilder method like `MigrationBuilder::createFunctionalIndex(***)` for this cases?

**Comment by samdark** [comment]
What's the error exactly?

**Comment by Gerych1984** [comment]
> What's the error exactly?

In yii2 arguments of createIndex method have not type hint like yii3. So if i put string "GIN" as 4th argument (bool $unique) like i do it in yii2 - i except php type error

![2021-09-22 23 02 19 github com 454ed1f906c7](https://user-images.githubusercontent.com/90403480/134414153-36440857-f412-4927-9c04-ce0850dcb5be.jpg)
![2021-09-22 23 03 18 github com dbedb666a760](https://user-images.githubusercontent.com/90403480/134414155-c61e39da-223c-47b7-936d-671cefad176b.jpg)

**Comment by samdark** [comment]
How did it work with Yii2? I assume `GIN` was equal to `true` in this case, right?

**Comment by Gerych1984** [comment]
> How did it work with Yii2? I assume `GIN` was equal to `true` in this case, right?

No, that create [PgSql GIN/GIST/Hash index](https://postgrespro.ru/docs/postgrespro/13/textsearch-indexes) (not unique), because `yii\db\pgsql\QueryBuilder::createIndex` have condition for this case (like and yii3 `Yiisoft\Db\Pgsql\QueryBuilder::createIndex` has i see now), but in yii3 it useless with type hint bool of $unique.

[Yii2](https://github.com/yiisoft/yii2/blob/7332cc2cba32ab00d752b6a465aa0b366858d6c6/framework/db/pgsql/QueryBuilder.php#L118)

[Yii3](https://github.com/yiisoft/db-pgsql/blob/f2e74944f2647db2f7df8444371c2dad888dc0a7/src/QueryBuilder.php#L151)

So i propose - do not remove type hint and create more flexible method like 

```
createFunctionalIndex(string $name, string $table, $columns, string $using, bool $unique = false) 
{
         /** generate SQL
             CREATE ($unique ? 'UNIQUE' : '') INDEX ON $table USING $using($columns)
        * /      
}
```

Because PgSql can create function indexes, and we can create it like that
`$b->createFunctionalIndex('test_index', 'test_table', 'test_column', 'LOWER', true)`.

Thanks

**Comment by samdark** [comment]
I think it's better to have a separate method for the purpose rather than additional syntax as in Yii 2.

**Comment by vjik** [comment]
Done. `createIndex()` signature changed to:

```php
/**
     * Builds and executes a SQL statement for creating a new index.
     *
     * @param string $table The table that the new index will be created for. The table name will be properly quoted by
     * the method.
     * @param string $name The name of the index. The name will be properly quoted by the method.
     * @param array|string $columns The column(s) that should be included in the index. If there are multiple columns,
     * please separate them by commas or use an array. Each column name will be properly quoted by the method. Quoting
     * will be skipped for column names that include a left parenthesis "(".
     * @param string|null $indexType Type of index supported DBMS - for example: UNIQUE, FULLTEXT, SPATIAL, BITMAP or
     * `null` as default.
     * @param string|null $indexMethod For setting index organization method (with 'USING', not all DBMS).
     *
     * @throws Exception
     * @throws InvalidConfigException
     * @throws NotSupportedException
     *
     * @psalm-param string[]|string $columns
     */
    public function createIndex(
        string $table,
        string $name,
        array|string $columns,
        string|null $indexType = null,
        string|null $indexMethod = null
    ): void {
```
