### ISSUE TITLE
Add foreignKey method to ColumnSchemaBuilder for improve migration syntax

### ISSUE THREAD

**Issue by kfreiman** [yiisoft/db-migration#2]
It is enhancement. Add `foreignKey` method to `ColumnSchemaBuilder` for improve migration syntax
### What is the expected result?
```php
$this->createTable('table1', [
    'id' => $this->primaryKey(),
    'table2_id' => $this->integer()->foreignKey('name_of_fk', 'table2', 'id'),
]);
```
### What do you get instead?
```php
$this->createTable('table1', [
    'id' => $this->primaryKey(),
    'table2_id' => $this->integer(),
]);

$this->addForeignKey(
    'name_of_fk', 
    'table',
    'table2_id',
    'table2',
    'id'
);
```

**Comment by Tigrov** [comment]
Closed in favour #13

https://github.com/yiisoft/db-migration/issues/13#issuecomment-321755849

https://github.com/yiisoft/db-migration/issues/13#issuecomment-322033250
