### ISSUE TITLE
`MigrationBuilder::$maxSqlOutputLength` is always `0`

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/db-migration#205]
Any plans to use it? Or possible use it outside the pakage?

https://github.com/yiisoft/db-migration/blob/1ec213d71cd3bf88415ce8f70536b03955252a0b/src/MigrationBuilder.php#L20-L24

Used in one place
https://github.com/yiisoft/db-migration/blob/1ec213d71cd3bf88415ce8f70536b03955252a0b/src/MigrationBuilder.php#L50-L52

Initialized in one place
https://github.com/yiisoft/db-migration/blob/1ec213d71cd3bf88415ce8f70536b03955252a0b/src/Migrator.php#L157-L160

**Comment by vjik** [comment]
This option must be configurable. Suggest so way:

1) Add to `Migrator` constructor: 

```php
private ?int $maxSqlOutputLength = null
```

2) `$maxSqlOutputLength` in `MigrationBuilder` make mandatory.

3) Add this parameter to package configuration.

**Comment by vjik** [comment]
Done by #211
