### ISSUE TITLE
Rename bin utility `migration` to `yii-db-migration`

### ISSUE THREAD

**Issue by vjik** [yiisoft/db-migration#238]
Bin is global namespace, so we should use prefix `yii-`.

**Comment by samdark** [comment]
That's a bit too long to type.

**Comment by vjik** [comment]
By fact, it not need to type:

```
./ve[tab]/bin/yi[tab]
```

Bin is global namespace, so need use unique names:

![image](https://github.com/yiisoft/db-migration/assets/525501/519ed496-f681-4f97-b70c-1d25d40eb9d5)

But "migration" is too general name.

**Comment by arogachev** [comment]
As for the length - it's not much longer, plus auto-completion definitely helps as @vjik pointed out. And I also agree that "migration" name is quite common when used globally.
