### ISSUE TITLE
Yii2 migration name

### ISSUE THREAD

**Issue by hacan359** [yiisoft/db-migration#251]
**What steps will reproduce the problem?**

1. Upgrade from Yii2 to Yii3.
2. Encounter migration adaptation issues.
3. Notice that the migration package only includes files that match the regular expression '/^(M(\d{12}).*).php$/s'. [Yiisoft\Db\Migration\Service\MigrationService:152](https://github.com/yiisoft/db-migration/blob/05a51864e1f6f77cb8dbfc96ef6b2d386afba87b/src/Service/MigrationService.php#L152)
4. Observe that older migration filenames, such as 'm200516_100846_create_user', are not detected by the  migrator.

**What is the expected result?**
I expect the migration package to allow for customization of the filename pattern used for migration detection. This customization should enable the inclusion of migrations with filenames following the Yii2 convention, like 'm200516_100846_create_user'.

**What do you get instead?**
The current implementation restricts migration file inclusion to those matching the fixed regular expression '/^(M(\d{12}).*).php$/s', causing issues with migrations that don't conform to this specific  #pattern.

**Additional Information**
The ability to specify a custom filename pattern for migration detection would enhance the flexibility of the migration package and ease the transition for users upgrading from Yii2 to Yii3. This feature would allow users to continue using their existing migration filenames without modification, ensuring a smoother migration process.

UPDATE
I managed to create a solution that works with both old migrations from Yii2 and also with new ones.
[Yiisoft\Db\Migration\Service\MigrationService:152](https://github.com/yiisoft/db-migration/blob/05a51864e1f6f77cb8dbfc96ef6b2d386afba87b/src/Service/MigrationService.php#L152)
```php
if (is_file($path)) {
    $class = pathinfo($path, PATHINFO_FILENAME);
    $subject = $file;
    $pattern = '/\d+/';

    preg_match_all($pattern, $subject, $matches);
    $time = implode('', $matches[0]);

    if (!empty($namespace)) {
        $class = $namespace . '\\' . $class;
    }

    /** @psalm-var class-string $class */

    if (!isset($applied[$class])) {
        $migrations[$time . '\\' . $class] = $class;
    }
}
```
Example in db
<img width="979" alt="image" src="https://github.com/yiisoft/db-migration/assets/59626486/b46d0c20-d1df-43ba-a81b-3c9fc76556cb">

**Comment by samdark** [comment]
How do you run old migrations if their code isn't compatible?

**Comment by hacan359** [comment]
I have optimized the code in migrations to work with Yii3. Of course, it is possible to rename the class and file to comply with the new standards, but transitioning from Yii2 to Yii3 with the preservation of migration history is faster without this step. There are also other common approaches to migrating from Yii2 to Yii3. For instance, you can create a dump of the current database state and only save new migrations, or rename existing migrations according to the new standard. I would appreciate general recommendations on migrations when transitioning from Yii2 to Yii3. Thank you.

**Comment by samdark** [comment]
Since there's no 1 to 1 compatibility with Yii2 migrations, I think we should not include code to read migrations named in Yii2 format. I'd go with squashing Yii2 history to a dump and using it as a starting point for Yii3.

**Comment by samdark** [comment]
A recipie for migration is a good idea.

**Comment by hacan359** [comment]
Thanks for the answer, we'll do a dump

**Comment by hacan359** [comment]
Thanks for the answer, we'll do a dump
